Add Fanboy Newsletter list
brave/adblock-resources pull request #98
Opened 2023-02-01 01:10 UTC by ryanbr

Adds Fanboy's Anti-Newsletter List. Address: https://github.com/brave/brave-browser/issues/28115

Both PEM's uploaded too 1pass:

`ad-block-updater-690FF3B4-8B6B-4709-8505-fEC6643D7BD9.pem`
`ad-block-updater-key2-690FF3B4-8B6B-4709-8505-fEC6643D7BD9.pem`

2023-02-01 10:28 UTC, antonok-edm approved these changes

2023-02-01 10:30 UTC, antonok-edm requested changes
Can you rename the second PEM?

It should be

`ad-block-updater-kdddfellohomdnfkdhombbddhojklibj.pem`

Also the first one should use the updated uppercase UUID

2023-02-01 10:30 UTC, antonok-edm commented on filter_lists/regional.json
> +        "uuid": "690FF3B4-8B6B-4709-8505-fEC6643D7BD9",
UUID shouldn't contain any lowercase letters

2023-02-01 10:51 UTC, ryanbr commented
Renamed pems also

2023-02-27 11:24 UTC, ryanbr commented
Looks good @antonok-edm ?

2023-03-01 00:28 UTC, antonok-edm approved these changes

2023-03-01 00:30 UTC, merged